### ISSUE TITLE
6.0以上系统问题 

### ISSUE THREAD

**Issue by PeakJ** [tomisacatyet/AMap4Location#2]
安卓系统升级到6.0以上，没有默认赋予手机定位权限，也不弹窗询问，能否加入权限开启提示

**Comment by coolara** [comment]
作者 添加插件怎么加

**Comment by coolara** [comment]
http://lbs.amap.com/api/android-location-sdk/guide/utilities/permission/
这里是6。0 动态添加权限

**Comment by coolara** [comment]
cordova plugin add cordova-plugin-android-permissions@0.10.0 安装下这个插件 把定位的权限直接写在run里就可以了 不懂加我qq 772114880 注明git
